@startuml

User->Système : demande de coller

alt texte sélectionné
Système -> Système : supprime le texte sélectionné
Système -> Système : place le curseur à l'endroit où était le texte

end
Système -> Système : copie des caractères à la position du curseur

@enduml