@startuml

User->Système : demande de supprimer 
alt texte sélectionné
Système -> Système : suppression des caractères 
else pas de texte selectionné 
Système->Système: suppression du caractère devant le curseur
end



@enduml