@startuml

actor User as U

participant "system:System" as S
participant "restore:Restore" as C
participant "history:History" as H
participant "memento:Memento" as M
participant "file:File" as F
activate S

loop while we don't want to quit

alt
U -> S : enter a key event
else
U -> S : demand to quit
end

S -> S : update all events
activate S
deactivate S

S -> S : execute all commands
activate S

S -> C : execute()
activate C
C -> C : checkPreconditions()

C -> S : vérifie les evenements \nactifs



alt valid preconditions
C -> H : restore()
activate H
H->H : recupere le memento dans m_future
deactivate C
H->M : execute()
activate M
M -> F : restaure le texte  
activate F
deactivate F
M -> H : retourne un nouveau Memento\n (Inverse de celui actuel)
H->H : ajoute le memento à m_past
H->H: supprime l'ancien memento
destroy M

end
deactivate S
deactivate H
S -> S : print the document
activate S

S -> F : getContent()

S --> U : show file content
deactivate S

end

@enduml
